stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: klaasm/rmondocker:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34269
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
